name: aprender_a_leer
description: Una aplicación para aprender a leer usando sílabas, palabras e imágenes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.5
  shared_preferences: ^2.5.3
  flutter_tts: ^3.5.3
  uuid: ^3.0.7 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - lib/utils/images/
    - lib/utils/images/animales/
    - lib/utils/gifs/    # Cambiar videos por gifs

  # Si usas fuentes personalizadas, descomenta y configura esta sección
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700