import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';

const List<String> palabrasValidas = [
  "ABAJO", "ABRAZAR", "ABRIGO", "ABRIGOS", "ABRIR", "CAMA", "CAMAS",
  "AGUA", "ÁGUILA", "ÁGUILAS", "AHORA", "ALGO", "ALLÁ", "ALMOHADA", "ALMOHADAS",
  "ALTO", "ALTOS", "AMARILLO", "AMARILLOS", "AMIGA", "AMIGAS", "AMIGO", "AMIGOS",
  "AMOR", "ANDAR", "ANIMAL", "ANIMALES",
  "ANTES", "AQUÍ", "ARBOLES", "ÁRBOL", "ARBUSTO", "ARBUSTOS", "ARDILLA",
  "ARDILLAS", "ARENA", "ARENAS", "ARCOÍRIS", "ARMARIO", "ARMARIOS", "ASIENTO",
  "AVE", "AVES", "AURORA", "AURORAS", "AYER", "AZÚCAR", "AZUL", "AZULES",
  "BAILAR", "BAILES", "BAJO", "BAJOS", "BALLENA", "BALLENAS", "BARCO",
  "BARCOS", "BAÑO", "BAÑOS", "BEBÉ", "BEBÉS", "BEBER", "BIEN",
  "BIENES", "BICICLETA", "BICICLETAS", "BLANCA", "BLANCAS", "BLUSA", "BLUSAS",
  "BOLSO", "BOLSOS", "BOSQUE", "BOSQUES", "BOSTEZAR", "BOSTEZO", "BOSTEZOS",
  "BOTÓN", "BOTONES", "BRINCA", "BRINCAR", "BRISA", "BRISAS", "BÚHO",
  "BÚHOS", "BUFANDA", "BUFANDAS", "CABALLO", "CABALLOS", "CABRA", "CABRAS",
  "CACTUS", "CADA", "CAFÉ", "CALENDARIO", "CALENDARIOS", "CALIENTE", "CALIENTES",
  "CALLE", "CALMA", "CALOR", "CAMELLO", "CAMELLOS", 'CAMINA', "CAMINAR", "CAMINO", 
  "CAMISA", "CAMISAS", "CAMIÓN", "CAMIONES", "CAMPO", "CAMPOS", "CANDADO",
  "CANDADOS", "CANTA", "CANTAR", "CAOS", "CARACOL", "CARACOLES", "CARNE",
  "CARNES", "CARRETERA", "CARRO", "CARTÓN", "CARTONES", "CASA", "CASAS",
  "CELESTE", "CELESTES", "CERCA", "CERCANO", "CERCANOS", "CERDO", "CERDOS",
  "CERRAR", "CHICA", "CHICAS", "CHICO", "CHICOS",
  "CISNE", "CISNES", "CLARO", "CLAROS", "COCINA", "COCO", "COLCHÓN",
  "COLCHONES", "COLINA", "COLINAS", "COLOR", "COLORES", "COLUMNA", "COME",
  "COMEDOR", "COMEN", "COMER", "COMIENDO", "COMPAÑERO", "COMPAÑEROS", "COMPLEJO",
  "COMPLEJOS", "COMPLETO", "COMPLETOS", "CON", "CONEJO", "CONEJOS", "CORBATAS",
  "CORBATA", "CORTINA", "CORTINAS", "CREER", "CUADRADO", "CUADRADOS", "CUARTO",
  "CUARTOS", "CUCHARA", "CUCHARAS", "CUCHILLO", "CUCHILLOS", "DADO", "DADOS",
  "DEBAJO", "DEBER", "DECIR", "DICE", "DICEN", "DELFIN", "DENTRO",
  "DESAYUNA", "DESAYUNAN", "DESAYUNO", "DESAYUNOS", "DESIERTO", "DESIERTOS", "DESORDEN", "DESPUÉS", "DESTELLO",
  "DIBUJAR", "DIBUJO", "DIBUJOS", "DIFÍCIL", "DIFICULTAD", "DORMIR", "DORMITORIO",
  "DORMITORIOS", "DUDA", "DUDAS", "DURANTE", "ECHAR", "ECLIPSE", "ELEFANTE",
  "ELEFANTES", "ELLA", "ELLAS", "ELLOS", "EMPUJA", "EMPUJAN", "EMPUJAR",
  "ENTRADA", "ENTRADAS", "ENTRANDO", "ENTRAR", "ENVIAR", "EQUIPO", "EQUIPOS",
  "ERIZO", "ERIZOS", "ERROR", "ERRORES", 'ESCALA', 'ESCALAN', 'ESCALANDO', "ESCALERA", "ESCALERAS", "ESCALÓN",
  "ESCALONES", "ESCONDE", "ESCONDEN", "ESCONDIDO", "ESCONDIDOS", "ESCONDITE", "ESCRIBE",
  "ESCRIBEN", "ESCRIBIR", "ESCRITORIO", "ESCRITORIOS", "ESCUCHAR", "ESFERA", "ESMERALDA",
  "ESMERALDAS", "ESPACIO", "ESPACIOS", "ESPIRAL", "ESTAR", "ESTRELLA", "ESTRELLAS",
  "ESTUDIO", "ESTUDIOS", "ESTUFA", "ESTUFAS", "FÁCIL", "FAMILIA", "FAMILIAS",
  "FE", "FELICES", "FELIZ", "FLAMENCO", "FLAMENCOS", "FLOR", "FLORES",
  "FRESA", "FRESAS", "FRÁGIL", "FRÍO", "FROTAR", "FUEGO", "FUEGOS",
  "FUENTE", "FUENTES", "FUERA", "FUERTE", "FUGAZ", "GALAXIA", "GALAXIAS",
  "GALLO", "GALLOS", "GARAJE", "GARAJES", "GATO", "GATOS", "GIRA",
  "GIRANDO", "GIRAR", "GIRÓ", "GORILA", "GORILAS", "GORRA", "GORRAS",
  "GORRO", "GORROS", "GRANDE", "GRANDES", "GRIS", "GUANTE", "GUANTES",
  "GUERRA", "GUERRAS", "HABLAR", "HACER", "HACIA", "HIELO", "HIJO",
  "HIJOS", "HOGAR", "HOGARES", "HOJA", "HOJAS", "HOLA", "HONGO", "HONGOS",
  "HORMIGA", "HORMIGAS", "HOY", "HUECO", "HUELLA", "HUELLAS", "IDEA",
  "IDEAS", "IGLESIA", "IGLESIAS", "IGUAL", "ISLA", "ISLAS", "IRSE",
  "JABALÍ", "JABALÍES", "JARDÍN", "JARDINES", "JUGAR", "LAGO", "LAGOS",
  "LÁMPARA", "LÁMPARAS", "LANZAR", "LECHE", "LEER", "LEJANA", "LEJANAS",
  "LEJANO", "LEJANOS", "LEJOS", "LENTEJA", "LENTEJAS", "LENTO", "LLAVE",
  "LLAVES", "LOBO", "LOBOS", "LUCES", "LUZ", "MAGIA", "MAMÁ",
  "MIEL", "PANTUFLA", "PANTUFLAS", "POSTE", "POSTES", "RUBÍ", "RUBI",
  "RUEDA", "RUEDAS", "RODRIGUEZ", "SOLIS"
];

const List<String> silabasEspeciales = [
  "A", "AL", "DA", "DE", "EL", "EN", "ES", "FE", "HA", "LA",
  "LE", "LAS", "LOS", "LUZ", "ME", "MI", "MAS", "MES", "MIS", "NI",
  "NO", "QUE", "QUI", "SE", "SI", "SU", "TE", "TU", "UN", "VA",
  "VE", "VI", "WEB", "WI", "Y", "YA", "YO",
];

final List<String> iniciosDePalabras3Silabas = [
  'CELU', 'CARGA', 'MANZA', 'CAMI', 'VENTA', 'ESCUE', 'MONTA',
  'AMI', 'ABRA', 'ABRI', 'ÁGUI', 'ANI', 'ARBO', 'ARBUS', 
  'ARDI', 'ARE', 'ARMA', 'ASIEN', 'AURO', 'AZÚ', 'AZU', 
  'BALLE', 'BOSTE', 'BOTO', 'BUFAN', 'CABA', 'CALIEN', 'CAME', 
  'CAMI', 'CANDA', 'CARA', 'CARTO', 'CELES', 'CERCA', 'COCI', 
  'COLCHO', 'COLI', 'COLO', 'COLUM', 'COME', 'COMIEN', 'COMPLE', 
  'CONE', 'CORBA', 'CORTI', 'CUADRA', 'CUCHA', 'CUCHI', 'DEBA', 
  'DESIER', 'DESOR', 'DIBU', 'DIFÍ', 'DURAN', 'ECLIP', 'EMPU', 
  'ENTRA', 'ENTRAN', 'EQUI', 'ERI', 'ERRO', 'ESCA', 'ESCON', 
  'ESCRI', 'ESCU', 'ESFE', 'ESPA', 'ESPI', 'ESTRE', 'FELI', 
  'FLAMEN', 'GALA', 'GARA', 'GIRAN', 'GORI', 'HORMI', 'IGLE', 
  'JABA', 'JARDI', 'LÁMPA', 'LEJA', 'LENTE', 'PANTU', 'RODRI', 
  'ESTU', 'FAMI', 
];

final List<String> iniciosDePalabras4Silabas = [
  'CHOCOLA', 'BIBLIOTE', 'FAMILI', 'MARIPO', 'AUTOMO', 'IMPRESO', 
  'ALMOHA', 'AMARI', 'ANIMA', 'ARCOÍ', 'BICICLE', 'CALENDA', 'CAMIO', 
  'CARRETE', 'COMPAÑE', 'DESAYU', 'DIFICUL', 'DORMITO', 'ELEFAN', 'ESCALE', 
  'ESCALAN', 'ESCALO', 'ESCONDI', 'ESCRITO', 'ESMERAL',
];

const double blockWidth = 60.0;
const double blockHeight = 40.0;
const double blockSpacing = 8.0;